const data = [
    {
        "id": 1,
        "NoColli": 1,
        "Weight": 2.5,
        "StarIps": "19240899",
        "SAPPO": "0050408744",
        "NoItem": 4,
        "Qty": 1,
        "UM": "JGO",
        "Descripcion": "CAPACITY CONTROL SLIDE KIT, 5000600",
        "MaterialCode": "10326599",
        "Country": "Italy",
        "Currency": "EUR",
        "USDCost": "527.34",
        "TotalUSDCost": "527.34",
        "TariffCode": "0",
        "Kit": [
            {
                "Id": "1.1",
                "kitId": 749,
                "bultos": 1,
                "cantidad": 2,
                "costo": 200,
                "costoTotal": 400,
                "currency": "USD",
                "descripcion": "aaa",
                "numeroposicion": null,
                "numitems": null,
                "paisorigen": 2,
                "paisorigenName": "Utd.Arab Emir.",
                "partidaId": 178221,
                "peso": 3,
                "unidadMedida": 1,
                "unidadMoneda": 2,
                "unit": "JHR"
            },
            {
                "Id": "1.2",
                "kitId": 750,
                "bultos": 1,
                "cantidad": 1,
                "costo": 100,
                "costoTotal": 100,
                "currency": "USD",
                "descripcion": "xxxx",
                "numeroposicion": null,
                "numitems": null,
                "paisorigen": 2,
                "paisorigenName": "Utd.Arab Emir.",
                "partidaId": 178221,
                "peso": 3,
                "unidadMedida": 1,
                "unidadMoneda": 2,
                "unit": "JHR"
            },
            {
                "Id": "1.3",
                "kitId": 751,
                "bultos": 1,
                "cantidad": 1,
                "costo": 27.34,
                "costoTotal": 27.34,
                "currency": "USD",
                "descripcion": "ssss",
                "numeroposicion": null,
                "numitems": null,
                "paisorigen": 1,
                "paisorigenName": "Andorran",
                "partidaId": 178221,
                "peso": 3,
                "unidadMedida": 1,
                "unidadMoneda": 2,
                "unit": "JHR"
            },{
                "Id": "1.4",
                "kitId": 751,
                "bultos": 1,
                "cantidad": 1,
                "costo": 27.34,
                "costoTotal": 27.34,
                "currency": "USD",
                "descripcion": "ssss",
                "numeroposicion": null,
                "numitems": null,
                "paisorigen": 1,
                "paisorigenName": "Andorran",
                "partidaId": 178221,
                "peso": 3,
                "unidadMedida": 1,
                "unidadMoneda": 2,
                "unit": "JHR"
            },{
                "Id": "1.5",
                "kitId": 751,
                "bultos": 1,
                "cantidad": 1,
                "costo": 27.34,
                "costoTotal": 27.34,
                "currency": "USD",
                "descripcion": "ssss",
                "numeroposicion": null,
                "numitems": null,
                "paisorigen": 1,
                "paisorigenName": "Andorran",
                "partidaId": 178221,
                "peso": 3,
                "unidadMedida": 1,
                "unidadMoneda": 2,
                "unit": "JHR"
            }
        ]
    },
    {
        "id": 2,
        "NoColli": 0,
        "Weight": 0,
        "StarIps": "19240899",
        "SAPPO": "0050408744",
        "NoItem": 5,
        "Qty": 1,
        "UM": "PZA",
        "Descripcion": "EVAPORATOR FLOW SWITCH, DAIKIN, 360279P",
        "MaterialCode": "10326616",
        "Country": "Italy",
        "Currency": "EUR",
        "USDCost": "508.54",
        "TotalUSDCost": "508.54",
        "TariffCode": "0",
        "Kit": [{
            "Id": "2.1",
            "kitId": 749,
            "bultos": 1,
            "cantidad": 2,
            "costo": 200,
            "costoTotal": 400,
            "currency": "USD",
            "descripcion": "aaa",
            "numeroposicion": null,
            "numitems": null,
            "paisorigen": 2,
            "paisorigenName": "Utd.Arab Emir.",
            "partidaId": 178221,
            "peso": 3,
            "unidadMedida": 1,
            "unidadMoneda": 2,
            "unit": "JHR"
        }]
    },
    {
        "id": 3,
        "NoColli": 0,
        "Weight": 0,
        "StarIps": "19240899",
        "SAPPO": "0050408744",
        "NoItem": 6,
        "Qty": 1,
        "UM": "PZA",
        "Descripcion": "DISCHARGE SHUT-OFF VALVE, 5015439",
        "MaterialCode": "10326622",
        "Country": "Italy",
        "Currency": "EUR",
        "USDCost": "15.51",
        "TotalUSDCost": "15.51",
        "TariffCode": "0",
        "Kit": []
    },
    {
        "id": 4,
        "NoColli": 0,
        "Weight": 0,
        "StarIps": "19240899",
        "SAPPO": "0050408744",
        "NoItem": 8,
        "Qty": 1,
        "UM": "PZA",
        "Descripcion": "MAIN SWITCH , DAIKIN, 5000882",
        "MaterialCode": "10326648",
        "Country": "Italy",
        "Currency": "EUR",
        "USDCost": "1,016.61",
        "TotalUSDCost": "1,016.61",
        "TariffCode": "0",
        "Kit": []
    },
    {
        "id": 5,
        "NoColli": 0,
        "Weight": 0,
        "StarIps": "19240899",
        "SAPPO": "0050408744",
        "NoItem": 9,
        "Qty": 1,
        "UM": "PZA",
        "Descripcion": "PRIMARY TRANSFORMER, DAIKIN, 5003965",
        "MaterialCode": "10326652",
        "Country": "Italy",
        "Currency": "EUR",
        "USDCost": "229.59",
        "TotalUSDCost": "229.59",
        "TariffCode": "0",
        "Kit": []
    }
];

export default data;